#!/usr/bin/env ruby
#
#

require "bundler"
Bundler.require(:default)
# require "google_drive"

require './lib/put_in_spreadsheet'

o = PutIn::Spreadsheet.new(
  spreadsheet_id: "1cPN5gfuor4mJ1jOsM9IEHtJ1E-OjC38TJb_VP2cQbN0")

ws = o.ws

p ws[2, 1]

binding.pry
