---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bug-scrub-dev
bases:
  - ../automated

patchesStrategicMerge:
  - bug-scrub-web-patch.yaml
  - ingress-patch.yaml
  - gitrepo-patch.yaml
  - imageauto-patch.yaml
