---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bug-scrub
resources:
  - ../base

  # - namespace.yaml
  # - deployment.yaml
  # - _ingress.yaml

patchesStrategicMerge:
  - bug-scrub-patch.yaml
  - ingress-patch.yaml
