---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: latest-any
  namespace: bug-scrub
spec:
  imageRepositoryRef:
    name: bug-scrub-web
  filterTags:
    pattern: '^.*-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: edge
  namespace: bug-scrub
spec:
  imageRepositoryRef:
    name: bug-scrub-web
  filterTags:
    pattern: '^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(-edge\.\d*)?$'
  policy:
    semver:
      range: ^0.x-0
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: edge-config
  namespace: bug-scrub
spec:
  imageRepositoryRef:
    name: bug-scrub-web-config
  filterTags:
    pattern: '^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(-edge\.\d*)?$'
  policy:
    semver:
      range: ^0.x-0
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: prerelease
  namespace: bug-scrub
spec:
  imageRepositoryRef:
    name: bug-scrub-web
  policy:
    semver:
      range: '>=0.0.0 <1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: stable
  namespace: bug-scrub
spec:
  imageRepositoryRef:
    name: bug-scrub-web
  policy:
    semver:
      range: '>=1.0.0'
