---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bug-scrub-auto
resources:
  - namespace.yaml
  - configrepo.yaml
  - imagerepo.yaml
  - imagepolicy.yaml
  # read-write for image update automation
  - imageauto.yaml
  - bug-scrub-rw-gitrepo.yaml
  - _bug-scrub-web-deployment.yaml
  - _ingress.yaml

patchesStrategicMerge:
  - bug-scrub-web-patch.yaml
  - ingress-patch.yaml
