name: Flux Push OCI Release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'release/*'

jobs:
  flux:
    env:
      IMAGE: ghcr.io/kingdonb/river-data-explorer-config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - uses: actions/setup-go@v4
      #   with:
      #     go-version: '^1.17.0'

      # Use Flux to publish mkdocs build output as OCI
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      # Harvest the GIT_TAG in case this is a tag, for OCI
      - name: Prepare
        id: prep
        run: |
          GIT_TAG=${GITHUB_REF/refs\/tags\/release\//}
          echo ::set-output name=GIT_TAG::${GIT_TAG}

      - name: Login to GHCR
        uses: docker/login-action@v2
        if: github.event_name == 'push' && github.ref_type == 'tag'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Flux push OCI Repository
        id: oci_push
        if: github.event_name == 'push' && github.ref_type == 'tag'
        run: |
          flux push artifact oci://${{ env.IMAGE }}:${{ steps.prep.outputs.GIT_TAG }} \
            --path="./deploy" \
            --source="$(git config --get remote.origin.url)" \
            --revision="$(git branch --show-current)/$(git rev-parse HEAD)"
